- name: Aktualizacja urządzeń MikroTik RouterOS (przez REST API v7)
  hosts: mikrotik_devices
  gather_facts: false

  connection: httpapi

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: community.network.routeros

    ansible_user: "{{ mikrotik_user }}+cet512w"
    ansible_password: "{{ mikrotik_password }}"

  tasks:
    - name: Enable vlan filtering on bridge
      community.network.routeros_command:
        commands: /system/routerboard/print
      register: results

    - debug:
        var: results

  # connection: httpapi

  # vars:
  #   ansible_httpapi_plugin: community.routeros.routeros_rest
  #   ansible_user: "{{ mikrotik_user }}+cet512w"
  #   ansible_password: "{{ mikrotik_password }}"

  #   ansible_httpapi_use_ssl: yes
  #   ansible_httpapi_validate_certs: no
  #   ansible_command_timeout: 60

  # tasks:
  #   - name: Pobranie informacji o wersji (sprawdzenie połączenia)
  #     community.routeros.api:
  #       path: /system/resource
  #     register: current_version_check
  #     changed_when: false

  #   - name: Wyświetlenie obecnej wersji
  #     ansible.builtin.debug:
  #       msg: "Obecna wersja: {{ current_version_check.result[0].version }}"

  #   - name: Sprawdzenie, czy jest dostępna nowa wersja RouterOS
  #     community.routeros.api:
  #       path: /system/package/update/check-for-updates
  #     register: update_check
  #     changed_when: update_check.result[0].status == "New version is available"




  # tasks:
  #   - name: Pobranie informacji o wersji (sprawdzenie połączenia)
  #     # Używamy modułu httpapi_command zamiast community.routeros.api
  #     ansible.netcommon.httpapi_command:
  #       # Ścieżkę podajemy w parametrze 'command'
  #       command: /system/resource
  #     register: current_version_check
  #     changed_when: false

  #   - name: Wyświetlenie obecnej wersji
  #     ansible.builtin.debug:
  #       # Wynik JSON jest teraz w kluczu '.json' (a nie '.result')
  #       # Ścieżka REST /system/resource zwraca obiekt, a nie listę
  #       msg: "Obecna wersja: {{ current_version_check.json.version }}"

  #   - name: Sprawdzenie, czy jest dostępna nowa wersja RouterOS
  #     ansible.netcommon.httpapi_command:
  #       command: /system/package/update/check-for-updates
  #       # Ta operacja wymaga metody POST
  #       method: post
  #     register: update_check
  #     # Wynik jest w .json, a nie .result[0]
  #     changed_when: update_check.json.status == "New version is available"

  #   - name: Wyświetlenie statusu aktualizacji
  #     ansible.builtin.debug:
  #       msg: "Status aktualizacji: {{ update_check.json.status }}"
