---
- name: Aktualizacja urządzeń MikroTik RouterOS (przez REST API v7)
  hosts: mikrotik_devices
  gather_facts: false

  connection: httpapi

  vars:
    ansible_httpapi_plugin: community.routeros.routeros_rest
    ansible_user: "{{ mikrotik_user }}+cet512w"
    ansible_password: "{{ mikrotik_password }}"

    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_command_timeout: 20

  tasks:
    - name: Pobranie informacji o wersji (sprawdzenie połączenia)
      community.routeros.api:
        path: /system/resource
      register: current_version_check
      changed_when: false

    - name: Wyświetlenie obecnej wersji
      ansible.builtin.debug:
        msg: "Obecna wersja: {{ current_version_check.result[0].version }}"

    # ... (reszta zadań z Twojego zakomentowanego bloku) ...

    - name: Sprawdzenie, czy jest dostępna nowa wersja RouterOS
      community.routeros.api:
        path: /system/package/update/check-for-updates
      register: update_check
      changed_when: update_check.result[0].status == "New version is available"
