---
- name: Aktualizacja urządzeń MikroTik RouterOS
  hosts: mikrotik_devices
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_user: "{{ mikrotik_user }}"
    ansible_network_os: community.routeros.routeros

  tasks:
    - name: Ustawienie stabilnej gałęzi aktualizacji
      community.routeros.command:
        commands: /system/package/update/set channel=stable
      changed_when: false

    - name: Sprawdzenie dostępnych aktualizacji RouterOS
      community.routeros.command:
        commands: /system/package/update/check-for-updates without-paging
      register: update_check
      changed_when: "'New version is available' in (update_check.stdout | join(''))"
      notify: Reboot device if needed

    - name: Dostępne wersje
      ansible.builtin.debug:
        msg: "Dostępna nowa wersja: {{ update_check.stdout_lines[0]['latest-version'] }}. Obecna wersja: {{ update_check.stdout_lines[0]['current-version'] }}"
      when: update_check.changed

    - name: Pobranie pakietu aktualizacyjnego
      community.routeros.command:
        commands: /system/package/update/download
      when: update_check.changed
      register: download_status
      changed_when: "'Downloaded' in (download_status.stdout | join(''))"

  # ---------------------------------------------------------------------------
  # HANDLERS - Zadania wywoływane przez "notify"
  # ---------------------------------------------------------------------------
  handlers:
    - name: Reboot device if needed
      block:
        - name: Restart urządzenia...
          community.routeros.command:
            commands: /system/reboot
          async: 45
          poll: 0

        - name: Oczekiwanie na ponowne uruchomienie urządzenia (port SSH)
          ansible.builtin.wait_for:
            host: "{{ inventory_hostname }}"
            port: 22
            state: started
            delay: 30
            timeout: 300
          delegate_to: localhost

        - name: Weryfikacja wersji po aktualizacji
          community.routeros.command:
            commands: /system resource print without-paging
          register: final_version_check
          changed_when: false

        - name: Wyświetlenie finalnej wersji RouterOS
          ansible.builtin.debug:
            msg: "Urządzenie {{ inventory_hostname }} zaktualizowane do wersji: {{ final_version_check.stdout_lines[0].version }}"
