---
- name: Aktualizacja urządzeń MikroTik RouterOS (Wersja uproszczona)
  hosts: mikrotik_devices
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_user: "{{ mikrotik_user }}"
    ansible_network_os: community.routeros.routeros

  tasks:
    - name: Ustawienie stabilnej gałęzi aktualizacji (stable)
      community.routeros.command:
        commands: /system/package/update/set channel=stable
      changed_when: false

    - name: Sprawdzenie, czy jest dostępna nowa wersja RouterOS
      community.routeros.command:
        commands: /system/package/update/check-for-updates
      register: update_check
      changed_when: "'New version is available' in (update_check.stdout | join(''))"

    - name: Wyświetlenie informacji o dostępnej wersji (jeśli znaleziono)
      ansible.builtin.debug:
        msg: "Dostępna nowa wersja: {{ update_check.stdout_lines[0]['latest-version'] }}. Obecna wersja: {{ update_check.stdout_lines[0]['current-version'] }}"
      when: update_check.changed

    - name: Proces aktualizacji i restartu urządzenia
      block:
        - name: Pobranie pakietu aktualizacyjnego
          community.routeros.command:
            commands: /system/package/update/download
          register: download_status
          changed_when: "'Downloaded' in (download_status.stdout | join(''))"

        - name: Restart urządzenia w celu instalacji aktualizacji
          community.routeros.command:
            commands: /system/reboot
          async: 45
          poll: 0

        - name: Oczekiwanie na ponowne uruchomienie urządzenia (port SSH)
          ansible.builtin.wait_for:
            host: "{{ inventory_hostname }}"
            port: 22
            state: started
            delay: 30
            timeout: 300
          delegate_to: localhost

        - name: Weryfikacja wersji po aktualizacji (z ponowieniami)
          community.routeros.command:
            commands: /system/resource/print
          register: final_version_check
          until: final_version_check.failed == false
          retries: 10
          delay: 15
          changed_when: false

        - name: Wyświetlenie finalnej wersji RouterOS
          ansible.builtin.debug:
            msg: "SUKCES: Urządzenie {{ inventory_hostname }} zaktualizowane do wersji: {{ final_version_check.stdout_lines[0].version }}"

      when: update_check.changed
