---
- name: System Update (Debian Native)
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Ensure python3-apt is installed (Bootstrap)
      ansible.builtin.raw: apt-get update && apt-get install -y python3-apt
      changed_when: false
      failed_when: false

    - name: Gather Facts
      ansible.builtin.setup:

    - name: Update cache, upgrade dist, and clean up
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoclean: yes
        autoremove: yes
        cache_valid_time: 3600
      register: apt_result

    - name: Check if reboot-required file exists
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Display reboot status
      ansible.builtin.debug:
        msg: >-
          System status:
          {{ 'Reboot REQUIRED' if reboot_required_file.stat.exists else 'No reboot needed' }}.
          (Updates changed: {{ apt_result.changed }})

    - name: Reboot system if required
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible after Debian Trixie update"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 5
        post_reboot_delay: 60
        test_command: uptime
      when: reboot_required_file.stat.exists
